#!/bin/sh

#  ETHER-1 Service Node docker template
#  Copyright © 2019 cryon.io
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#  Contact: cryi@tutanota.com

BASEDIR=$(dirname "$0")

if [ -f "$BASEDIR/project_id" ]; then
    PROJECT=$(sed 's/PROJECT=//g' "$BASEDIR/project_id")
    #PROJECT="--project-name $PROJECT"
else
    frffl=""
fi

if [ ! -f "$BASEDIR/../docker-compose.override.yml" ]; then
    mdwcf=""
fi

container=$(for c in $(docker-compose -f "$BASEDIR/docker-compose.yml" ${mdwcf-"-f"} ${mdwcf-"$OVERRIDE_COMPOSE_FILE"} ${frffl-"--project-name"} ${frffl-"$PROJECT"} ps -q mn 2>/dev/null); do
    if [ "$(docker inspect -f '{{.State.Running}}' "$c" 2>/dev/null)" = "true" ]; then
        printf "%s" "$c"
        break
    fi
done)

docker exec --user etho "$container" /usr/sbin/geth-etho "$@"